[package]
name = "rfc5389"
version = "0.1.0"
authors = ["matsub <matsub.rk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
