version: '3'

services:
  rust:
    build: rust
    networks:
      - sugoi

#  stun-server:
#    build: stun-tester
#    networks:
#      - sugoi

  stun-client:
    build: stun-tester
    command: ["/usr/bin/turnutils_stunclient", "rust"]
    depends_on:
      - rust
    networks:
      - sugoi

networks:
  sugoi:
    driver: bridge
